# Generated by Django 3.2.7 on 2022-01-01 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_data_result'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
    ]
